blank_issues_enabled: false
contact_links:
  - name: "Sonic User Community - Sonic用户社区"
    url: https://sonic-cloud.wiki/
    about: You can also communicate in the user community. 您也可以前往用户社区交流。
  - name: "Sonic Official Website - Sonic官方网站"
    url: https://sonic-cloud.cn/
    about: You can also go to Sonic official website to find documents. 您也可以前往Sonic官方网站查找文档。
